# Generated by Django 5.1.3 on 2024-12-02 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminapi", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userroombooking",
            name="user_role",
            field=models.CharField(
                choices=[
                    ("Staff", "Staff"),
                    ("Student", "Student"),
                    ("Faculty", "Faculty"),
                    ("Admin", "Admin"),
                ],
                default=0,
                max_length=10,
            ),
        ),
    ]
