# Generated by Django 5.1.3 on 2024-11-30 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserRoomBooking",
            fields=[
                (
                    "user_id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("username", models.CharField(max_length=100, unique=True)),
                ("password", models.CharField(max_length=100)),
                ("firstname", models.CharField(max_length=100)),
                ("lastname", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=150, unique=True)),
                ("phone_no", models.CharField(max_length=10)),
                ("address_street_no", models.IntegerField()),
                ("address_street_name", models.CharField(max_length=255)),
                ("address_city", models.CharField(max_length=100)),
                ("address_state", models.CharField(max_length=100)),
                ("address_country", models.CharField(max_length=100)),
                ("penalty_received", models.FloatField(blank=True, null=True)),
            ],
            options={
                "db_table": "user_roombooking",
            },
        ),
    ]
